
import { Case } from './types';

export const CASES: Case[] = [
  {
    id: 1,
    title: "Illustration to Figure",
    author: "@ZHO_ZHO_ZHO",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case1-input1/400/400"],
    outputImage: "/card-previews/illustration-to-figure.png",
    prompt: `turn this photo into a character figure. Behind it, place a box with the character's image printed on it, and a computer showing the Blender modeling process on its screen. In front of the box, add a round plastic base with the character figure standing on it. set the scene indoors if possible`,
    inputsNeeded: 1,
  },
  {
    id: 2,
    title: "Generate Ground View from Map Arrow",
    author: "@tokumin",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case2-input1/400/400"],
    outputImage: "/card-previews/generate-ground-view-from-map-arrow.png",
    prompt: `draw what the red arrow sees`,
    inputsNeeded: 1,
  },
  {
    id: 3,
    title: "Real World AR Information",
    author: "@bilawalsidhu",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case3-input1/400/400"],
    outputImage: "/card-previews/real-world-ar-information.png",
    prompt: `you are a location-based AR experience generator. highlight [point of interest] in this image and annotate relevant information about it.`,
    inputsNeeded: 1,
    note: "Need to input the point of interest to be annotated in the prompt [POI]",
  },
  {
    id: 4,
    title: "Extract 3D Buildings/Make Isometric Models",
    author: "@Zieeett",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case4-input1/400/400"],
    outputImage: "/card-previews/extract-3d-buildings-make-isometric-models.png",
    prompt: `Make Image Daytime and Isometric [Building Only]`,
    inputsNeeded: 1,
    note: "Modify the information in [brackets] as needed (can be set to vehicles, people, etc.)",
  },
  {
    id: 5,
    title: "Photos of Yourself in Different Eras",
    author: "@AmirMushich",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case5-input1/400/400"],
    outputImage: "/card-previews/photos-of-yourself-in-different-eras.png",
    prompt: `Change the character's style to [1970]'s classical [male] style. Add [long curly] hair, [long mustache], change the background to the iconic [californian summer landscape]. Don't change the character's face`,
    inputsNeeded: 1,
    note: "Change the text in [brackets] to your era and detail information",
  },
  {
    id: 6,
    title: "Multi-Reference Image Generation",
    author: "@MrDavids1",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case6-input1/400/400", "https://picsum.photos/seed/case6-input2/400/400", "https://picsum.photos/seed/case6-input3/400/400"],
    outputImage: "/card-previews/multi-reference-image-generation.png",
    prompt: `A model is posing and leaning against a pink bmw. She is wearing the following items, the scene is against a light grey background. The green alien is a keychain and it's attached to the pink handbag. The model also has a pink parrot on her shoulder. There is a pug sitting next to her wearing a pink collar and gold headphones.`,
    inputsNeeded: 3,
    note: "The prompt needs to describe in detail and include multiple reference objects",
  },
  {
    id: 7,
    title: "Automatic Photo Editing",
    author: "@op7418",
    category: "Photo & Realism",
    inputImages: ["https://picsum.photos/seed/case7-input1/400/400"],
    outputImage: "/card-previews/automatic-photo-editing.png",
    prompt: `This photo is very boring and plain. Enhance it! Increase the contrast, boost the colors, and improve the lighting to make it richer,You can crop and delete details that affect the composition.`,
    inputsNeeded: 1,
  },
  {
    id: 8,
    title: "Hand Drawing Controls Multi-Character Poses",
    author: "@op7418",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case8-input1/400/400", "https://picsum.photos/seed/case8-input2/400/400"],
    outputImage: "/card-previews/hand-drawing-controls-multi-character-poses.png",
    prompt: `Have these two characters fight using the pose from the sketch. Add appropriate visual backgrounds and scene interactions, Generated image ratio is 16:9`,
    inputsNeeded: 2,
  },
  {
    id: 9,
    title: "Cross-View Image Generation",
    author: "@op7418",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case9-input1/400/400"],
    outputImage: "/card-previews/cross-view-image-generation.png",
    prompt: `Convert the photo to a top-down view and mark the location of the photographer.`,
    inputsNeeded: 1,
  },
  {
    id: 10,
    title: "Custom Character Stickers",
    author: "@op7418",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case10-input1/400/400", "https://picsum.photos/seed/case10-input2/400/400"],
    outputImage: "/card-previews/custom-character-stickers.png",
    prompt: `Help me turn the character into a white outline sticker similar to the reference sticker. The character needs to be transformed into a web illustration style, and add a playful white outline short phrase describing the character.`,
    inputsNeeded: 2,
  },
   {
    id: 11,
    title: "Anime to Real Coser",
    author: "@ZHO_ZHO_ZHO",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case11-input1/400/400"],
    outputImage: "/card-previews/anime-to-real-coser.png",
    prompt: "Generate a photo of a girl cosplaying this illustration, with the background set at Comiket",
    inputsNeeded: 1,
  },
  {
    id: 12,
    title: "Generate Character Design Sheet",
    author: "@ZHO_ZHO_ZHO",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case12-input1/400/400"],
    outputImage: "/card-previews/generate-character-design-sheet.png",
    prompt: "Generate a character design sheet for me including proportion design, three views (front, side, back), expression sheet, pose sheet, and costume design.",
    inputsNeeded: 1,
  },
  {
    id: 13,
    title: "Color Line Art with Color Palette",
    author: "@ZHO_ZHO_ZHO",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case13-input1/400/400", "https://picsum.photos/seed/case13-input2/400/400"],
    outputImage: "/card-previews/color-line-art-with-color-palette.png",
    prompt: "Accurately use the color palette from the second image to color the character in the first image.",
    inputsNeeded: 2,
  },
  {
    id: 14,
    title: "Article Infographic",
    author: "@黄建同学",
    category: "Layout & Design",
    inputImages: [],
    outputImage: "/card-previews/article-infographic.png",
    prompt: `Generate an infographic for this article content: 'We present Nano-consistent-150k — the first dataset constructed using Nano-Banana that exceeds 150k high-quality samples...' Requirements: 1. Extract key information. 2. Keep the content in the image concise. 3. Use English text. 4. Add rich and cute cartoon characters and elements.`,
    inputsNeeded: 0,
  },
  {
    id: 15,
    title: "Change Multiple Hairstyles",
    author: "@balconychy",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case15-input1/400/400"],
    outputImage: "/card-previews/change-multiple-hairstyles.png",
    prompt: "Generate avatars of this person with different hairstyles in a 3x3 grid format.",
    inputsNeeded: 1,
  },
   {
    id: 16,
    title: "Model Annotation Explanation Diagram",
    author: "@berryxia_ai",
    category: "Layout & Design",
    inputImages: [],
    outputImage: "/card-previews/model-annotation-explanation-diagram.png",
    prompt: "Draw a 3D human heart model for an academic presentation, with annotations and explanations, suitable for showcasing its principles and each organ's functions, very realistic, highly detailed, with extremely fine design.",
    inputsNeeded: 0,
    note: "The model annotations are not always entirely accurate; please verify the information.",
  },
  {
    id: 17,
    title: "Custom Marble Sculpture",
    author: "@umesh_ai",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case17-input1/400/400"],
    outputImage: "/card-previews/custom-marble-sculpture.png",
    prompt: "A photorealistic image of an ultra-detailed sculpture of the subject in image made of shining marble. The sculpture should display smooth and reflective marble surface, emphasizing its luster and artistic craftsmanship. The design is elegant, highlighting the beauty and depth of marble. The lighting in the image should enhance the sculpture's contours and textures, creating a visually stunning and mesmerizing effect.",
    inputsNeeded: 1,
  },
  {
    id: 18,
    title: "Cook Based on Ingredients",
    author: "@Gdgtify",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case18-input1/400/400"],
    outputImage: "/card-previews/cook-based-on-ingredients.png",
    prompt: "make me a delicious lunch with these ingredients, and put it on a plate, zoomed in view of the plate, remove the other plates and ingredients.",
    inputsNeeded: 1,
  },
  {
    id: 19,
    title: "Math Problem Reasoning",
    author: "@Gorden Sun",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case19-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case19-output/400/300",
    prompt: "Write the answer to the problem in the corresponding position based on the question.",
    inputsNeeded: 1,
  },
  {
    id: 20,
    title: "Old Photo Colorization",
    author: "@GeminiApp",
    category: "Photo & Realism",
    inputImages: ["https://picsum.photos/seed/case20-input1/400/400"],
    outputImage: "/card-previews/old-photo-colorization.png",
    prompt: "restore and colorize this photo.",
    inputsNeeded: 1,
  },
  {
    id: 21,
    title: "OOTD Outfit Change",
    author: "@302.AI",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case21-input1/400/400", "https://picsum.photos/seed/case21-input2/400/400"],
    outputImage: "/card-previews/ootd-outfit-change.png",
    prompt: "Choose the person in the first Image and dress them in all the clothing and accessories from the second Image. Shoot a series of realistic OOTD-style photos outdoors, using natural lighting, a stylish street style, and clear full-body shots. Keep the person's identity and pose from the first Image, but show the complete outfit and accessories from the second Image in a cohesive, stylish way.",
    inputsNeeded: 2,
  },
  {
    id: 22,
    title: "Character Clothing Change",
    author: "@skirano",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case22-input1/400/400", "https://picsum.photos/seed/case22-input2/400/400"],
    outputImage: "/card-previews/character-clothing-change.png",
    prompt: "Replace the person's clothing in the input image with the target clothing shown in the reference image. Keep the person's pose, facial expression, background, and overall realism unchanged. Make the new outfit look natural, well-fitted, and consistent with lighting and shadows. Do not alter the person's identity or the environment — only change the clothes.",
    inputsNeeded: 2,
  },
  {
    id: 23,
    title: "Multi-View Result Generation",
    author: "@Error_HTTP_404",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case23-input1/400/400"],
    outputImage: "/card-previews/multi-view-result-generation.png",
    prompt: "Generate the Front, Rear, Left, Right, Top, Bottom views on white. Evenly spaced. Consistent subject. Isometric Perspective Equivalence.",
    inputsNeeded: 1,
  },
  {
    id: 24,
    title: "Movie Storyboard",
    author: "@GeminiApp",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case24-input1/400/400"],
    outputImage: "/card-previews/movie-storyboard.png",
    prompt: "Create an addictively intriguing 12 part story with 12 images with these two characters in a classic black and white film noir detective story. Make it about missing treasure that they get clues for throughout and then finally discover. The story is thrilling throughout with emotional highs and lows and ending on a great twist and high note. Do not include any words or text on the images but tell the story purely through the imagery itself.",
    inputsNeeded: 1,
  },
  {
    id: 25,
    title: "Character Pose Modification",
    author: "@arrakis_ai",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case25-input1/400/400"],
    outputImage: "/card-previews/character-pose-modification.png",
    prompt: "Have the person in the picture look straight ahead",
    inputsNeeded: 1,
  },
  {
    id: 26,
    title: "Generate Image from Line Drawing",
    author: "@ZHO_ZHO_ZHO",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case26-input1/400/400", "https://picsum.photos/seed/case26-input2/400/400"],
    outputImage: "/card-previews/generate-image-from-line-drawing.png",
    prompt: "Change the pose of the person in the first image to that of the second image, and shoot in a professional studio.",
    inputsNeeded: 2,
  },
  {
    id: 27,
    title: "Add Watermark to Image",
    author: "@AiMachete",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case27-input1/400/400"],
    outputImage: "/card-previews/add-watermark-to-image.png",
    prompt: "Watermark the word ‘TRUMP’ over and over again across the whole image.",
    inputsNeeded: 1,
  },
  {
    id: 28,
    title: "Knowledge Reasoning Image Generation",
    author: "@icreatelife",
    category: "Layout & Design",
    inputImages: [],
    outputImage: "/card-previews/knowledge-reasoning-image-generation.png",
    prompt: "Make me an infographic of 5 tallest buildings in the world",
    inputsNeeded: 0,
  },
  {
    id: 29,
    title: "Red Pen Annotations",
    author: "@AiMachete",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case29-input1/400/400"],
    outputImage: "/card-previews/red-pen-annotations.png",
    prompt: "Analyze this image. Use red pen to denote where you can improve.",
    inputsNeeded: 1,
  },
  {
    id: 30,
    title: "Explosive Food Photography",
    author: "@icreatelife",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case30-input1/400/400"],
    outputImage: "/card-previews/explosive-food-photography.png",
    prompt: "Photograph this product in a dramatic modern scene accompanied by explosive outward dynamic arrangement of the key ingredients fresh and raw flying around the product signifying its freshness and nutritional value. promo ad shot, without text, product is emphasized, with the key brand colors as background.",
    inputsNeeded: 1,
  },
  {
    id: 31,
    title: "Create Comic Book Strip",
    author: "@icreatelife",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case31-input1/400/400"],
    outputImage: "/card-previews/create-comic-book-strip.png",
    prompt: "Based on the uploaded image, make a comic book strip, add text, write a compelling story. I want a superhero comic book.",
    inputsNeeded: 1,
  },
  {
    id: 32,
    title: "Custom Action Figure",
    author: "@icreatelife",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case32-input1/400/400"],
    outputImage: "/card-previews/custom-action-figure.png",
    prompt: "make an action figure of me that says [“AI Evangelist - Kris”] and features [coffee, turtle, laptop, phone and headphones]",
    inputsNeeded: 1,
    note: "Change the text in [brackets] to the items you want to add.",
  },
  {
    id: 33,
    title: "Map to Isometric Buildings",
    author: "@demishassabis",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case33-input1/400/400"],
    outputImage: "/card-previews/map-to-isometric-buildings.png",
    prompt: "Take this location and make the landmark an isometric image (building only), in the style of the game Theme Park",
    inputsNeeded: 1,
  },
  {
    id: 34,
    title: "Control Character Expression",
    author: "@ZHO_ZHO_ZHO",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case34-input1/400/400", "https://picsum.photos/seed/case34-input2/400/400"],
    outputImage: "/card-previews/control-character-expression.png",
    prompt: "Character reference from the first Image. Change to the expression from the second Image.",
    inputsNeeded: 2,
  },
  {
    id: 35,
    title: "Illustration Drawing Process",
    author: "@ZHO_ZHO_ZHO",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case35-input1/400/400"],
    outputImage: "/card-previews/illustration-drawing-process.png",
    prompt: "Generate a four-panel drawing process for the character: Step 1: Line art, Step 2: Flat colors, Step 3: Add shadows, Step 4: Refine and complete. No text.",
    inputsNeeded: 1,
  },
  {
    id: 36,
    title: "Virtual Makeup Try-On",
    author: "@ZHO_ZHO_ZHO",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case36-input1/400/400", "https://picsum.photos/seed/case36-input2/400/400"],
    outputImage: "/card-previews/virtual-makeup-try-on.png",
    prompt: "Apply the makeup from the second image to the character in the first image, while maintaining the pose from the first image.",
    inputsNeeded: 2,
  },
  {
    id: 37,
    title: "Makeup Analysis",
    author: "@ZHO_ZHO_ZHO",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case37-input1/400/400"],
    outputImage: "/card-previews/makeup-analysis.png",
    prompt: "Analyze this image. Use a red pen to mark areas that can be improved for makeup.",
    inputsNeeded: 1,
  },
  {
    id: 38,
    title: "Google Maps View of Middle-earth",
    author: "@TechHallo",
    category: "Fun & Creative",
    inputImages: [],
    outputImage: "/card-previews/google-maps-view-of-middle-earth.png",
    prompt: "Dashcam Google Street View shot | Hobbiton Street | hobbits carrying out daily tasks like gardening and smoking pipes | Sunny weather",
    inputsNeeded: 0,
    note: "Change the text to the desired location and weather.",
  },
  {
    id: 39,
    title: "Typographic Illustration",
    author: "@Umesh",
    category: "Art & Illustration",
    inputImages: [],
    outputImage: "/card-previews/typographic-illustration.png",
    prompt: "Create a minimalist black-and-white typographic illustration of the scene 'riding a bicycle' using only the letters in the phrase. Each letter should be creatively shaped or positioned to form the rider, the bicycle, and a sense of motion. The design should be clean, ultra-minimalist, and entirely composed of the modified letters without adding any extra shapes or lines.",
    inputsNeeded: 0,
  },
  {
    id: 40,
    title: "Multiple Character Poses",
    author: "@tapehead_Lab",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case40-input1/400/400"],
    outputImage: "/card-previews/multiple-character-poses.png",
    prompt: "Please create a pose sheet for this illustration, making various poses!",
    inputsNeeded: 1,
  },
  {
    id: 41,
    title: "Product Packaging Generation",
    author: "@ZHO_ZHO_ZHO",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case41-input1/400/400", "https://picsum.photos/seed/case41-input2/400/400"],
    outputImage: "/card-previews/product-packaging-generation.png",
    prompt: "Apply the design from the first image to the can in the second image, and place it in a minimalist design setting, professional photography.",
    inputsNeeded: 2,
  },
  {
    id: 42,
    title: "Overlay Filter/Material",
    author: "@ZHO_ZHO_ZHO",
    category: "Photo & Realism",
    inputImages: ["https://picsum.photos/seed/case42-input1/400/400", "https://picsum.photos/seed/case42-input2/400/400"],
    outputImage: "/card-previews/overlay-filter-material.png",
    prompt: "Overlay the [glass] effect from the second image onto the photo in the first image.",
    inputsNeeded: 2,
    note: "Change the text in [brackets] to the desired filter/material.",
  },
  {
    id: 43,
    title: "Control Character Face Shape",
    author: "@ZHO_ZHO_ZHO",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case43-input1/400/400", "https://picsum.photos/seed/case43-input2/400/400"],
    outputImage: "/card-previews/control-character-face-shape.png",
    prompt: "Design the character from the first image as a chibi version according to the face shape from the second image.",
    inputsNeeded: 2,
  },
  {
    id: 44,
    title: "Lighting Control",
    author: "@ZHO_ZHO_ZHO",
    category: "Photo & Realism",
    inputImages: ["https://picsum.photos/seed/case44-input1/400/400", "https://picsum.photos/seed/case44-input2/400/400"],
    outputImage: "/card-previews/lighting-control.png",
    prompt: "Change the character from the first image to the lighting from the second image, with dark areas as shadows.",
    inputsNeeded: 2,
  },
  {
    id: 45,
    title: "LEGO Minifigure",
    author: "@ZHO_ZHO_ZHO",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case45-input1/400/400"],
    outputImage: "/card-previews/lego-minifigure.png",
    prompt: `Transform the person in the photo into a LEGO minifigure packaging box style, presented in isometric perspective. Label the box with the title "ZHOGUE". Inside the box, display the LEGO minifigure based on the person in the photo, along with their essential items (such as makeup, bags, or other items) as LEGO accessories. Beside the box, also display the actual LEGO minifigure itself, unpackaged, rendered in a realistic and vivid style.`,
    inputsNeeded: 1,
  },
  {
    id: 46,
    title: "Gundam Model Figure",
    author: "@ZHO_ZHO_ZHO",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case46-input1/400/400"],
    outputImage: "/card-previews/gundam-model-figure.png",
    prompt: `Transform the person in the photo into a Gundam model kit packaging box style, presented in isometric perspective. Label the box with the title "ZHOGUE". Inside the box, display a Gundam-style mechanical version of the person from the photo. Beside the box, also display the actual Gundam-style mechanical figure itself, outside the packaging, rendered in a realistic and lifelike style.`,
    inputsNeeded: 1,
  },
  {
    id: 47,
    title: "Hardware Exploded View",
    author: "@AIimagined",
    category: "Layout & Design",
    inputImages: [],
    outputImage: "/card-previews/hardware-exploded-view.png",
    prompt: "Exploded view of a DSLR showing all its accessories and internal components such as lens, filter, internal components, sensor, screws, buttons, viewfinder, housing, and circuit board. Maintain red accents of the DSLR.",
    inputsNeeded: 0,
  },
  {
    id: 48,
    title: "Food Calorie Annotation",
    author: "@icreatelife",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case48-input1/400/400"],
    outputImage: "/card-previews/food-calorie-annotation.png",
    prompt: "annotate this meal with names of food and calorie density and approximate calories.",
    inputsNeeded: 1,
  },
  {
    id: 49,
    title: "Extract Subject on Transparent Layer",
    author: "@nglprz",
    category: "Photo & Realism",
    inputImages: ["https://picsum.photos/seed/case49-input1/400/400"],
    outputImage: "/card-previews/extract-subject-on-transparent-layer.png",
    prompt: "extract the [samurai] and put transparent background.",
    inputsNeeded: 1,
    note: "Replace the text in [brackets] with the object you need to extract.",
  },
  {
    id: 50,
    title: "Image Outpainting Repair",
    author: "@bwabbage",
    category: "Photo & Realism",
    inputImages: ["https://picsum.photos/seed/case50-input1/400/400"],
    outputImage: "/card-previews/image-outpainting-repair.png",
    prompt: "Repair the checkerboard (transparent) parts of the image and restore a complete, coherent photo.",
    inputsNeeded: 1,
  },
  {
    id: 51,
    title: "Ancient Map to Historical Photo",
    author: "@levelsio",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case51-input1/400/400"],
    outputImage: "/card-previews/ancient-map-to-historical-photo.png",
    prompt: "full colour photograph. New Amsterdam in 1660. make sure it's full modern colors as if it's a photograph taken today.",
    inputsNeeded: 1,
  },
  {
    id: 52,
    title: "Fashion Moodboard Collage",
    author: "@tetumemo",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case52-input1/400/400"],
    outputImage: "/card-previews/fashion-moodboard-collage.png",
    prompt: "A fashion mood board collage. Surround a portrait with cutouts of the individual items the model is wearing. Add handwritten notes and sketches in a playful, marker-style font, and include the brand name and source of each item in English. The overall aesthetic should be creative and cute.",
    inputsNeeded: 1,
  },
  {
    id: 53,
    title: "Delicate Cute Product Photo",
    author: "@azed_ai",
    category: "Products & Mockups",
    inputImages: [],
    outputImage: "/card-previews/delicate-cute-product-photo.png",
    prompt: "A high-resolution advertising photograph of a realistic, miniature [PRODUCT] held delicately between a person's thumb and index finger. clean and white background, studio lighting, soft shadows. The hand is well-groomed, natural skin tone, and positioned to highlight the product’s shape and details. The product appears extremely small but hyper-detailed and brand-accurate, centered in the frame with a shallow depth of field. Emulates luxury product photography and minimalist commercial style.",
    inputsNeeded: 0,
    note: "Replace the text in [brackets] with the product you want to showcase.",
  },
  {
    id: 54,
    title: "Place Anime Statue in Real Life",
    author: "@riddi0908",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case54-input1/400/400"],
    outputImage: "/card-previews/place-anime-statue-in-real-life.png",
    prompt: "A realistic photographic work. A gigantic statue of this person has been placed in a square in the center of Tokyo, with people looking up at it.",
    inputsNeeded: 1,
  },
  {
    id: 55,
    title: "Create an Itasha Car",
    author: "@riddi0908",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case55-input1/400/400"],
    outputImage: "/card-previews/create-an-itasha-car.png",
    prompt: "Create a professional photograph of a sporty car with anime-style character artwork as itasha (painted car) design, shot at a famous tourist destination or scenic landmark. The car features large, prominently displayed anime character illustrations with simple, clean design composition. The character artwork should be painted in vibrant anime art style with bold colors and clear details.",
    inputsNeeded: 1,
  },
  {
    id: 56,
    title: "Manga Composition",
    author: "@namaedousiyoka",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case56-input1/400/400", "https://picsum.photos/seed/case56-input2/400/400"],
    outputImage: "/card-previews/manga-composition.png",
    prompt: "Use the character from the first image and place them in the composition of the second image, in a manga style.",
    inputsNeeded: 2,
  },
  {
    id: 57,
    title: "Manga Style Conversion",
    author: "@nobisiro_2023",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case57-input1/400/400"],
    outputImage: "/card-previews/manga-style-conversion.png",
    prompt: "Convert the input photo into a black-and-white manga-style line drawing.",
    inputsNeeded: 1,
  },
  {
    id: 58,
    title: "Isometric Holographic Wireframe",
    author: "@tetumemo",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case58-input1/400/400"],
    outputImage: "/card-previews/isometric-holographic-wireframe.png",
    prompt: "Based on the uploaded image, convert it into a holographic depiction using wireframe lines only.",
    inputsNeeded: 1,
  },
  {
    id: 59,
    title: "Minecraft-Style Scene Generation",
    author: "@tetumemo",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case59-input1/400/400"],
    outputImage: "/card-previews/minecraft-style-scene-generation.png",
    prompt: "Using this location, create an isometric HD-2D Minecraft-style image of the landmark (buildings only).",
    inputsNeeded: 1,
  },
  {
    id: 60,
    title: "Apply Material Sphere to Logo",
    author: "@ZHO_ZHO_ZHO",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case60-input1/400/400", "https://picsum.photos/seed/case60-input2/400/400"],
    outputImage: "/card-previews/apply-material-sphere-to-logo.png",
    prompt: "Apply the material from the second image to the logo in the first image, present it as a 3D object, render in a C4D-like style, with a solid-color background.",
    inputsNeeded: 2,
  },
  {
    id: 61,
    title: "Floor Plan 3D Render",
    author: "@op7418",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case61-input1/400/400"],
    outputImage: "/card-previews/floor-plan-3d-render.png",
    prompt: "Convert this residential floor plan into an isometric, photo-realistic 3D rendering of the house.",
    inputsNeeded: 1,
  },
  {
    id: 62,
    title: "Reset Camera Parameters",
    author: "@hckinz",
    category: "Photo & Realism",
    inputImages: ["https://picsum.photos/seed/case62-input1/400/400"],
    outputImage: "/card-previews/reset-camera-parameters.png",
    prompt: "RAW-ISO [100] - [F2.8-1/200 24mm] settings",
    inputsNeeded: 1,
    note: "Replace the values in [brackets] with your desired camera parameters.",
  },
  {
    id: 63,
    title: "Create an ID Photo",
    author: "@songguoxiansen",
    category: "Photo & Realism",
    inputImages: ["https://picsum.photos/seed/case63-input1/400/400"],
    outputImage: "/card-previews/create-an-id-photo.png",
    prompt: "Crop the head and create a 2-inch ID photo with: 1. Blue background, 2. Professional business attire, 3. Frontal face, 4. Slight smile.",
    inputsNeeded: 1,
  },
  {
    id: 64,
    title: "Scene A6 Folding Card",
    author: "@Gdgtify",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case64-input1/400/400"],
    outputImage: "/card-previews/scene-a6-folding-card.png",
    prompt: "Draw an A6 folding card of this scene: when opened, it reveals a complete 3D spherical tiny house with a miniature paper garden and a bonsai tree inside.",
    inputsNeeded: 1,
  },
  {
    id: 65,
    title: "Design a Chess Set",
    author: "@Gdgtify",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case65-input1/400/400"],
    outputImage: "/card-previews/design-a-chess-set.png",
    prompt: "Draw a chessboard and a set of 3D-printable chess pieces inspired by this image.",
    inputsNeeded: 1,
  },
  {
    id: 66,
    title: "Split-Contrast Style Photo",
    author: "@fofrAI",
    category: "Fun & Creative",
    inputImages: [],
    outputImage: "/card-previews/split-contrast-style-photo.png",
    prompt: "A photo of a bedroom split down the middle: the left side is 2018 and the right side is 1964, in the same room.",
    inputsNeeded: 0,
  },
  {
    id: 67,
    title: "Jewelry Collection Design",
    author: "@Gdgtify",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case67-input1/400/400"],
    outputImage: "/card-previews/jewelry-collection-design.png",
    prompt: "Transform this image into a 5-piece jewelry collection.",
    inputsNeeded: 1,
  },
  {
    id: 68,
    title: "Merchandise Design",
    author: "@0xFramer",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case68-input1/400/400"],
    outputImage: "/card-previews/merchandise-design.png",
    prompt: "Create merchandise using this character image.",
    inputsNeeded: 1,
  },
  {
    id: 69,
    title: "Model Holographic Projection",
    author: "@UNIBRACITY",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case69-input1/400/400"],
    outputImage: "/card-previews/model-holographic-projection.png",
    prompt: "Ultra-realistic product photo. Subject: virtual holographic character from the input image, floating above a circular hologram projector on a modern desk. The hologram is generated from the input image displayed on a modern PC monitor on the desk.",
    inputsNeeded: 1,
  },
  {
    id: 70,
    title: "Giant Figure Scaffolding",
    author: "@songguoxiansen",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case70-input1/400/400"],
    outputImage: "/card-previews/giant-figure-scaffolding.png",
    prompt: "A hyper-realistic 3D render of the person in the image as a giant figure, standing and taking a selfie. The giant figure is surrounded by massive scaffolding, with many tiny construction workers working on it. The scene is set in a city square, surrounded by modern buildings, moving vehicles, and pedestrians under a bright clear blue sky.",
    inputsNeeded: 1,
  },
  {
    id: 71,
    title: "Building Extraction from Remote Sensing",
    author: "@lehua555",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case71-input1/400/400"],
    outputImage: "/card-previews/building-extraction-from-remote-sensing.png",
    prompt: "Remove everything in the image except the buildings.",
    inputsNeeded: 1,
  },
  {
    id: 72,
    title: "Component Extraction",
    author: "@tetumemo",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case72-input1/400/400"],
    outputImage: "/card-previews/component-extraction.png",
    prompt: "Cut out each component and create a model sheet that retains the hologram.",
    inputsNeeded: 1,
  },
  {
    id: 73,
    title: "Remove Burger Ingredients",
    author: "@bind_lux",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case73-input1/400/400"],
    outputImage: "/card-previews/remove-burger-ingredients.png",
    prompt: "Remove all the ingredients from the burger and keep only the top and bottom buns. Leave a gap between them, keeping the same spacing as if the fillings were still inside.",
    inputsNeeded: 1,
  },
  {
    id: 74,
    title: "High-Resolution Image Restoration",
    author: "@op7418",
    category: "Photo & Realism",
    inputImages: ["https://picsum.photos/seed/case74-input1/400/400"],
    outputImage: "/card-previews/high-resolution-image-restoration.png",
    prompt: "Enhance the resolution of this old image and add the appropriate texture details, reinterpreting it with modern anime techniques.",
    inputsNeeded: 1,
  },
  {
    id: 75,
    title: "Generate Miniature Scene from Image",
    author: "@techhalla",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case75-input1/400/400"],
    outputImage: "/card-previews/generate-miniature-scene-from-image.png",
    prompt: "Convert the image to isometric view.",
    inputsNeeded: 1,
  },
  {
    id: 76,
    title: "Educational Comic",
    author: "@op7418",
    category: "Layout & Design",
    inputImages: [],
    outputImage: "https://picsum.photos/seed/case76-output/400/300",
    prompt: `Help me generate multiple 16:9 doodle-style images to explain the concept of "futures" to middle school students. The images should have a consistent colorful, thick-pencil hand-drawn style, be rich in information, feature English text, use solid color backgrounds, have outlines around the cards, and include uniform titles, similar to a PowerPoint presentation.`,
    inputsNeeded: 0,
  },
  {
    id: 77,
    title: "Custom Character Emoji Pack",
    author: "@vista8",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case77-input1/400/400", "https://picsum.photos/seed/case77-input2/400/400"],
    outputImage: "https://picsum.photos/seed/case77-output/400/300",
    prompt: "Using the character from the second image, generate 8 emoji stickers based on various poses from the first image.",
    inputsNeeded: 2,
  },
  {
    id: 78,
    title: "Restore Partially Eaten Food",
    author: "@googlejapan",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case78-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case78-output/400/300",
    prompt: "Restore this half-eaten donut back to its original uneaten state.",
    inputsNeeded: 1,
  },
  {
    id: 79,
    title: "Fighting Game Interface Creation",
    author: "@NanoBanana_labs",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case79-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case79-output/400/300",
    prompt: "Create a mid motion action scene where both subjects are in focus with a Three-Quarter Angle in martial arts fighting stances. They are in the same cinematic scene. Remove the line down the centre with a blurred crumbling ruins in a purple alien world in the background. The scene is shot at sunrise. Modern Fighting game health bars MORDON V'S DEATHSEED. power move. Hud style screen effects. Add a thumbnail of each character to the health bars.",
    inputsNeeded: 1,
  },
  {
    id: 80,
    title: "Model Cross-Section",
    author: "@old_pgmrs_will",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case80-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case80-output/400/300",
    prompt: "Create a cutaway visualization of this car, show exterior intact on one side, and interior engine + seats exposed on the other side. Keep proportions accurate and details realistic.",
    inputsNeeded: 1,
  },
  {
    id: 81,
    title: "Pirate Wanted Poster",
    author: "@AI_Kei75",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case81-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case81-output/400/300",
    prompt: "Using the original image, recreate a pirate's wanted poster drawn on parchment. Brown monochrome, with the texture of aged parchment. Retain the style and character design of the original image and paste it large at the top of the wanted poster. Have the character wear a pirate hat. Write a random bounty amount at the bottom of the poster.",
    inputsNeeded: 1,
  },
  {
    id: 82,
    title: "Merchandise Display Shelf",
    author: "@tokyo_Valentine",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case82-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case82-output/400/300",
    prompt: "Remove the background from this illustration and turn it into merchandise like figurines. Place them on the shelves of a fictional convenience store. The cute, pop atmosphere is complemented by neatly arranged merchandise featuring the illustration. The store's interior is dreamily bright and special. Include figures, acrylic stands, and plush toys.",
    inputsNeeded: 1,
  },
  {
    id: 83,
    title: "Comic Convention Booth",
    author: "@tokyo_Valentine",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case83-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case83-output/400/300",
    prompt: "A spacious Comic Market booth is filled with merchandise based on the character, lined up on tables and shelves. The atmosphere is filled with excitement and anticipation. A large figure is displayed in the center. A cosplayer of the character is holding a figurine in the center of the screen.",
    inputsNeeded: 1,
  },
  {
    id: 84,
    title: "Line Art to Doodle Drawing",
    author: "@hAru_mAki_ch",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case84-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case84-output/400/300",
    prompt: "Make the uploaded picture look as if it was drawn by a five-year-old child.",
    inputsNeeded: 1,
  },
  {
    id: 85,
    title: "Contemporary Art Exhibition Space",
    author: "@UNIBRACITY",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case85-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case85-output/400/300",
    prompt: "An avant-garde contemporary art exhibition space themed around the reference image. The entire exhibition hall integrates architecture, lighting, flooring, walls, and ceiling into the artistic expression. At the far end of the hall stands a massive wall where the theme from the reference image is presented in a monumental artistic form.",
    inputsNeeded: 1,
  },
  {
    id: 86,
    title: "Dark Gothic Tarot Card",
    author: "@ImperfectEngel",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case86-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case86-output/400/300",
    prompt: "Generate a dark gothic tarot card featuring me from this image. Include [“AI Artist - Shira”] and [coffee, white fluffy chubby cat with pink bow, laptop, phone, headphones] as symbols, with moody shadows, intricate gothic borders, and mystical dark fantasy vibes.",
    inputsNeeded: 1,
    note: "Replace the text inside [brackets] with your desired settings.",
  },
  {
    id: 87,
    title: "Black and White Evolution Chart",
    author: "@ZHO_ZHO_ZHO",
    category: "Fun & Creative",
    inputImages: [],
    outputImage: "https://picsum.photos/seed/case87-output/400/300",
    prompt: "Generate an evolutionary progression chart in a minimalist black-and-white style, showing the evolution from the earliest apes to humans and finally into a banana.",
    inputsNeeded: 0,
  },
  {
    id: 88,
    title: "Glass Bottle Souvenir",
    author: "@NanoBanana_labs",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case88-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case88-output/400/300",
    prompt: "A 1/7 scale commercialized collectible figure of the character from the photo, crafted in a highly realistic style. The figure is placed in a detailed beach environment with sand, seashells, and gentle ocean waves. The entire toy display is enclosed inside a clear souvenir glass bottle, giving it a premium miniature diorama look, with realistic lighting and shadows.",
    inputsNeeded: 1,
  },
  {
    id: 89,
    title: "Miniature Store",
    author: "@NanoBanana_labs",
    category: "Products & Mockups",
    inputImages: [],
    outputImage: "https://picsum.photos/seed/case89-output/400/300",
    prompt: "Tiny diorama shop for [BRAND]. Roof made of oversized [PRODUCT], big [BRAND] logo sign above the window, vendor handing a [PRODUCT] to a customer, ground covered with many [PRODUCT]. Hand-made polymer-clay look, studio macro photo, soft light, shallow depth of field, vertical 3:4",
    inputsNeeded: 0,
    note: "Replace the text inside [brackets] with your desired product.",
  },
  {
    id: 90,
    title: "Become a Vtuber",
    author: "@AI_Kei75",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case90-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case90-output/400/300",
    prompt: "Create a fictional Vtuber and their streaming screen using the original image. The Vtuber's hairstyle and clothing will be faithfully reproduced from the original image. Have the Vtuber hold a game controller. Place only the Vtuber's upper body in the bottom right of the screen. Place the streaming screen of the game being played in the center of the screen. Place the chat screen on the left side of the screen.",
    inputsNeeded: 1,
  },
  {
    id: 91,
    title: "Train Station Movie Poster",
    author: "@AI_Kei75",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case91-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case91-output/400/300",
    prompt: "Create a movie poster using the original image. The final generated image will be photorealistic. The scenery of the underground passage of a Japanese station where the poster is posted will be recreated in a realistic image. People passing through the underground passage will be added.",
    inputsNeeded: 1,
  },
  {
    id: 92,
    title: "Movie Lounge",
    author: "@tokyo_Valentine",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case92-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case92-output/400/300",
    prompt: "A photorealistic movie theater lounge. A special event-themed space, set in a popcorn stand, is decorated with the world of the characters from the image. Character merchandise is displayed on shelves. A cosplayer of the character is placed in the center of the screen.",
    inputsNeeded: 1,
  },
  {
    id: 93,
    title: "Slice Object with Cartoon Explosion",
    author: "@Arminn_Ai",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case93-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case93-output/400/300",
    prompt: "cut cleanly the [OBJECT] in half across the middle, the top and bottom halves slightly separated and floating apart. Between the halves, instead of the natural inside, there is a stylized cartoon nuclear explosion effect. The outside of the object remains photorealistic.",
    inputsNeeded: 1,
    note: "Replace the text inside [brackets] with your desired object.",
  },
  {
    id: 94,
    title: "Character-Themed Train",
    author: "@tokyo_Valentine",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case94-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case94-output/400/300",
    prompt: "A photorealistic Tokyo train interior. The entire car is decorated with character advertisements and merchandise from the input image. Several character cosplayers are standing in the foreground. Life-size figures are displayed in the back of the train.",
    inputsNeeded: 1,
  },
  {
    id: 95,
    title: "Custom Theme Park",
    author: "@AI_Kei75",
    category: "Scene & Environment",
    inputImages: ["https://picsum.photos/seed/case95-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case95-output/400/300",
    prompt: "Generates a photorealistic theme park image based on the original image. Daytime. Sunny. The color scheme and design are extracted from the original image and applied to various facilities. Vehicles and buildings based on the original image, mascot costumes, and signs are placed within the image.",
    inputsNeeded: 1,
  },
  {
    id: 96,
    title: "Create Constellation Image",
    author: "@AI_Kei75",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case96-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case96-output/400/300",
    prompt: "Create an image depicting fictional constellations using the original image as a reference. A photorealistic starry sky. People, animals, and objects extracted from the original image are placed transparently against the starry sky background. An imaginary constellation is created based on the placed motif, made up of approximately 5 to 10 stars.",
    inputsNeeded: 1,
  },
  {
    id: 97,
    title: "Turn Image into Phone Wallpaper",
    author: "@ZHO_ZHO_ZHO",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case97-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case97-output/400/300",
    prompt: "Transform the image into an iPhone lock screen wallpaper effect. The phone’s time, date, and status bar details appear overlaid on the image. The original picture is adapted to fit the elongated smartphone screen composition. The phone is placed against a background in the same color scheme.",
    inputsNeeded: 1,
  },
  {
    id: 98,
    title: "Make a Movie Poster",
    author: "@aiehon_aya",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case98-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case98-output/400/300",
    prompt: "Analyze the uploaded photo and detect the subject, mood, and atmosphere. Based on the detected genre, generate a cinematic movie title, a short tagline, a credit block, and a release note in English. Overlay these elements on the image in a movie-poster style layout.",
    inputsNeeded: 1,
  },
  {
    id: 99,
    title: "Turn X Account into Floppy Disk",
    author: "@icreatelife",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case99-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case99-output/400/300",
    prompt: "Make my X account into a floppy disk in the 90s.",
    inputsNeeded: 1,
  },
  {
    id: 100,
    title: "Make Object Transparent",
    author: "@icreatelife",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case100-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case100-output/400/300",
    prompt: "Make this object transparent.",
    inputsNeeded: 1,
  },
  {
    id: 101,
    title: "Fisheye Peephole Illustration",
    author: "@emakiscroll",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case101-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case101-output/400/300",
    prompt: "ultra-detailed anime illustration, fisheye lens peephole perspective, circular distorted view as if looking through a door peephole, warped wide-angle effect with curved edges. Two people from the input image leaning their faces close to the peephole trying to peek through, both with mischievous playful smiles.",
    inputsNeeded: 1,
  },
  {
    id: 102,
    title: "Superhero Interior Design",
    author: "@IqraSaifiii",
    category: "Scene & Environment",
    inputImages: [],
    outputImage: "https://picsum.photos/seed/case102-output/400/300",
    prompt: "A hyper-realistic, professional interior design photograph of a modern living room inspired by a [Superhero]. The room has clean lines, a neutral color palette of greys, blacks, and whites, with accents of [Theme Color]. A large, stylized 3D wall sculpture of the [Superhero] dominates the main wall.",
    inputsNeeded: 0,
    note: "Replace the text inside [brackets] with the information you need.",
  },
  {
    id: 103,
    title: "Custom Claw Machine",
    author: "@googlejapan",
    category: "Products & Mockups",
    inputImages: ["https://picsum.photos/seed/case103-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case103-output/400/300",
    prompt: "Generate an image showing this animal as a simplified and deformed anime-like plush toy, with multiple units inside a UFO catcher machine. The setting is a Japanese game center. The background is a wall, and the area behind the UFO catcher is quite blurred.",
    inputsNeeded: 1,
  },
  {
    id: 104,
    title: "Typography Logo Design",
    author: "@aziz4ai",
    category: "Layout & Design",
    inputImages: [],
    outputImage: "https://picsum.photos/seed/case104-output/400/300",
    prompt: "Create a typographic illustration shaped like a {OBJECT}, where the text itself forms the shape — bold and playful lettering style that fills the entire silhouette — letters adapt fluidly to the curves and contours of the object — vibrant and contrasting color palette that fits the theme — background is solid and enhances the focus on the main shape.",
    inputsNeeded: 0,
    note: "Replace the text inside curly braces with your desired object.",
  },
  {
    id: 105,
    title: "RPG Character Status UI",
    author: "@AI_Kei75",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case105-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case105-output/400/300",
    prompt: "Use the character in the original image to create a character status screen for an RPG game. Keep the character design but change the costume to one from a fantasy RPG. Display the character and the status screen side by side. The status screen should list various parameters, skills, icons, etc. The background should be a fantasy background.",
    inputsNeeded: 1,
  },
  {
    id: 106,
    title: "Convert Text Diagram to Pictograms",
    author: "@nobisiro_2023",
    category: "Layout & Design",
    inputImages: ["https://picsum.photos/seed/case106-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case106-output/400/300",
    prompt: "Convert this explanatory diagram into pictograms.",
    inputsNeeded: 1,
  },
  {
    id: 107,
    title: "Drawing on a Pen Display",
    author: "@AI_Kei75",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case107-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case107-output/400/300",
    prompt: "Photorealistic pen tablet screen. Realistic first-person hand holding the pen tablet and pen. The original image is reproduced on the pen tablet in an unfinished state. The line art has been extracted from the original image. Portions of the line art have been colored with the same coloring as the original image. Unfinished coloring. About 70% of the coloring is done.",
    inputsNeeded: 1,
  },
  {
    id: 108,
    title: "Create LINE Stamp Image",
    author: "@emakiscroll",
    category: "Character & Posing",
    inputImages: ["https://picsum.photos/seed/case108-input1/400/400", "https://picsum.photos/seed/case108-input2/400/400"],
    outputImage: "https://picsum.photos/seed/case108-output/400/300",
    prompt: "Create a character sheet of facial expressions: joy, anger, sadness, happiness. Use the character from the second image and the expressions from the first.",
    inputsNeeded: 2,
  },
  {
    id: 109,
    title: "Therapy for Childhood Self",
    author: "@samann_ai",
    category: "Fun & Creative",
    inputImages: ["https://picsum.photos/seed/case109-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case109-output/400/300",
    prompt: "Photorealistic minimalist therapy room; light walls, grey sofa. The same person at two ages sits side-by-side: adult (from input image) on the left speaking with open hands; child on the right listening with head slightly down. Both wear matching [OUTFIT] (same color & style).",
    inputsNeeded: 1,
    note: "Replace the text inside [brackets] with your desired outfit.",
  },
  {
    id: 110,
    title: "Pixar-Style Portrait",
    author: "@NanoBanana_labs",
    category: "Art & Illustration",
    inputImages: ["https://picsum.photos/seed/case110-input1/400/400"],
    outputImage: "https://picsum.photos/seed/case110-output/400/300",
    prompt: "3D avatar of the young man in the image attached, smiling happily, clean white background, conceptual digital art in Pixar-style, high quality, soft lighting, smooth textures, vibrant colors, realistic proportions with a cartoon touch & studio render look.",
    inputsNeeded: 1,
  },
];
