services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:3001"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    container_name: creative-image-studio
    restart: unless-stopped
