name = "create-image-studio"
compatibility_date = "2023-05-18"
pages_build_output_dir = "dist"

# Production environment
[env.production]
name = "create-image-studio"

# Preview environment
[env.preview]
name = "create-image-studio-preview"
